### ISSUE TITLE
Obsolete words in dictionary

### ISSUE THREAD

**Issue by avenmia** [wilt00/lgtm#3]
@wilt00 

When using the application I noticed that the word "thoght" appeared. At first, I **thought** this was a misspelled "thought", but after googling it turned out to be a real word but is obsolete.

https://github.com/wilt00/lgtm/blob/2d40a65ec4e12c8662315ee0b8376f96814fb6a2/lgtm/src/dicts/t.txt#L7544

According to [Wikipedia](https://en.wiktionary.org/wiki/thoght), "thoght" is obsolete. 

Please Fix.

Does not LGTM.

**Comment by wilt-rally** [comment]
This is an issue with an upstream dependency which we vendor: https://github.com/dwyl/english-words

Please report to that repo

\#wontfix

**Comment by wilt00** [comment]
This is an issue with an upstream dependency which we vendor: https://github.com/dwyl/english-words

Please report to that repo

\#wontfix
